name: stroke_prediction
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - dill
  - flake8
  - flask
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - xgboost
  - pip:
    - imbalanced-learn
    - python-dotenv
    - mkdocs
    - -e .